In [1]:
import pandas as pd

In [6]:
# Tripchains original
df1.set_index('TripChainId', inplace=True)

In [7]:
# Tripchains reverse
df2.set_index('TripChainId', inplace=True)

In [58]:
df1.head(2)

            OrigZoneId DestZoneId      Purpose TimePeriod
TripChainId
0            E02000313  E02000314  HB_FromHome         IP
0            E02000314  E02000313    HB_ToHome         IP

In [64]:
df2.loc[13]

,OrigZoneId,DestZoneId,Purpose,TimePeriod,tmp
TripChainId,,,,,
13,E02000313,E02000314,HB_FromHome,IP,E02000313E02000314HB_FromHomeIP
13,E02000314,E02000318,NHB_NonHomeBased,IP,E02000314E02000318NHB_NonHomeBasedIP
13,E02000318,E02006786,NHB_NonHomeBased,IP,E02000318E02006786NHB_NonHomeBasedIP
13,E02006786,E02000313,HB_ToHome,PM,E02006786E02000313HB_ToHomePM

In [60]:
cols = ['OrigZoneId', 'DestZoneId', 'Purpose', 'TimePeriod']
df1['tmp'] = df1[cols].values.sum(axis=1)
df2['tmp'] = df2[cols].values.sum(axis=1)

In [61]:
dfg1 = df1.groupby(level=0)['tmp'].sum()
dfg2 = df2.groupby(level=0)['tmp'].sum()

In [67]:
t1 = dfg1.reset_index()
t2 = dfg2.reset_index()

t1.set_index('tmp', inplace=True)
t2.set_index('tmp', inplace=True)

In [72]:
jn = t1.join(t2, lsuffix='_orig', rsuffix='_reverse')

In [95]:
l = pd.merge(t1, t2, how='outer', left_index=True, right_index=True)
l

,TripChainId_x,TripChainId_y
tmp,,
E02000313E02000314HB_FromHomeIPE02000314E02000313HB_ToHomeIP,0.0,0
E02000313E02000314HB_FromHomeIPE02000314E02000315NHB_NonHomeBasedIPE02000315E02006786NHB_NonHomeBasedIPE02006786E02000313HB_ToHomeIP,NaN,1
E02000313E02000314HB_FromHomeIPE02000314E02000315NHB_NonHomeBasedIPE02000315E02006786NHB_NonHomeBasedIPE02006786E02000313HB_ToHomePM,NaN,2
E02000313E02000314HB_FromHomeIPE02000314E02000315NHB_NonHomeBasedIPE02000315E09000004NHB_NonHomeBasedPME09000004E02000313HB_ToHomePM,NaN,3
E02000313E02000314HB_FromHomeIPE02000314E02000316NHB_NonHomeBasedIPE02000316E02006786NHB_NonHomeBasedIPE02006786E02000313HB_ToHomeIP,NaN,4
E02000313E02000314HB_FromHomeIPE02000314E02000316NHB_NonHomeBasedIPE02000316E02006786NHB_NonHomeBasedIPE02006786E02000313HB_ToHomePM,NaN,5
E02000313E02000314HB_FromHomeIPE02000314E02000316NHB_NonHomeBasedIPE02000316E02006786NHB_NonHomeBasedPME02006786E02000313HB_ToHomePM,NaN,6
E02000313E02000314HB_FromHomeIPE02000314E02000316NHB_NonHomeBasedIPE02000316E09000004NHB_NonHomeBasedIPE09000004E02000313HB_ToHomeIP,NaN,7
E02000313E02000314HB_FromHomeIPE02000314E02000316NHB_NonHomeBasedIPE02000316E09000004NHB_NonHomeBasedIPE09000004E02000313HB_ToHomePM,NaN,8
E02000313E02000314HB_FromHomeIPE02000314E02000316NHB_NonHomeBasedIPE02000316E09000004NHB_NonHomeBasedPME09000004E02000313HB_ToHomePM,NaN,9
E02000313E02000314HB_FromHomeIPE02000314E02000316NHB_NonHomeBasedIPE02000316E09000030NHB_NonHomeBasedIPE09000030E02000313HB_ToHomePM,NaN,10
E02000313E02000314HB_FromHomeIPE02000314E02000316NHB_NonHomeBasedIPE02000316E09000030NHB_NonHomeBasedPME09000030E02000313HB_ToHomePM,NaN,11
E02000313E02000314HB_FromHomeIPE02000314E02000318NHB_NonHomeBasedIPE02000318E02006786NHB_NonHomeBasedIPE02006786E02000313HB_ToHomeIP,NaN,12
E02000313E02000314HB_FromHomeIPE02000314E02000318NHB_NonHomeBasedIPE02000318E02006786NHB_NonHomeBasedIPE02006786E02000313HB_ToHomePM,16.0,13
E02000313E02000314HB_FromHomeIPE02000314E02000318NHB_NonHomeBasedIPE02000318E09000004NHB_NonHomeBasedIPE09000004E02000313HB_ToHomeIP,NaN,14
E02000313E02000314HB_FromHomeIPE02000314E02000318NHB_NonHomeBasedIPE02000318E09000004NHB_NonHomeBasedIPE09000004E02000313HB_ToHomePM,NaN,15
E02000313E02000314HB_FromHomeIPE02000314E02000318NHB_NonHomeBasedIPE02000318E09000004NHB_NonHomeBasedPME09000004E02000313HB_ToHomePM,NaN,16
E02000313E02000314HB_FromHomeIPE02000314E02000318NHB_NonHomeBasedIPE02000318E09000030NHB_NonHomeBasedIPE09000030E02000313HB_ToHomePM,NaN,17
E02000313E02000314HB_FromHomeIPE02000314E02000319NHB_NonHomeBasedIPE02000319E09000004NHB_NonHomeBasedIPE09000004E02000313HB_ToHomeIP,NaN,18
E02000313E02000314HB_FromHomeIPE02000314E02000319NHB_NonHomeBasedIPE02000319E09000004NHB_NonHomeBasedIPE09000004E02000313HB_ToHomePM,NaN,19
E02000313E02000314HB_FromHomeIPE02000314E02000321NHB_NonHomeBasedIPE02000321E09000004NHB_NonHomeBasedIPE09000004E02000313HB_ToHomeIP,NaN,20
E02000313E02000314HB_FromHomeIPE02000314E02000321NHB_NonHomeBasedIPE02000321E09000004NHB_NonHomeBasedIPE09000004E02000313HB_ToHomePM,NaN,21
E02000313E02000314HB_FromHomeIPE02000314E02000321NHB_NonHomeBasedIPE02000321E09000004NHB_NonHomeBasedPME09000004E02000313HB_ToHomePM,25.0,22
E02000313E02000314HB_FromHomeIPE02000314E02006786NHB_NonHomeBasedIPE02006786E02000313HB_ToHomeIP,26.0,23
E02000313E02000314HB_FromHomeIPE02000314E02006786NHB_NonHomeBasedIPE02006786E02000313HB_ToHomePM,27.0,24
E02000313E02000314HB_FromHomeIPE02000314E02006786NHB_NonHomeBasedIPE02006786E09000004NHB_NonHomeBasedIPE09000004E02000313HB_ToHomeIP,NaN,26
E02000313E02000314HB_FromHomeIPE02000314E02006786NHB_NonHomeBasedIPE02006786E09000004NHB_NonHomeBasedIPE09000004E02000313HB_ToHomePM,30.0,27
E02000313E02000314HB_FromHomeIPE02000314E02006786NHB_NonHomeBasedIPE02006786E09000004NHB_NonHomeBasedPME09000004E02000313HB_ToHomePM,NaN,28
E02000313E02000314HB_FromHomeIPE02000314E02006786NHB_NonHomeBasedPME02006786E02000313HB_ToHomePM,28.0,25
E02000313E02000314HB_FromHomeIPE02000314E02006786NHB_NonHomeBasedPME02006786E09000004NHB_NonHomeBasedPME09000004E02000313HB_ToHomePM,NaN,29
...,...,...
E02006929E02006930HB_FromHomeOP1E02006930E02006927NHB_NonHomeBasedIPE02006927E09000030NHB_NonHomeBasedIPE09000030E02006929HB_ToHomeOP2,NaN,10678
E02006929E02006930HB_FromHomeOP1E02006930E02006929HB_ToHomeIP,21539.0,10680
E02006929E02006930HB_FromHomeOP1E02006930E02006929HB_ToHomeOP1,21540.0,10681
E02006929E02006930HB_FromHomeOP1E02006930E09000030NHB_NonHomeBasedIPE09000030E02006929HB_ToHomeIP,NaN,10685
E02006929E02006930HB_FromHomeOP1E02006930E09000030NHB_NonHomeBasedIPE09000030E02006929HB_ToHomeOP2,NaN,10686
E02006929E02006930HB_FromHomeOP1E02006930E09000030NHB_NonHomeBasedPME09000030E02006929HB_ToHomeOP2,NaN,10687
E02006929E09000030HB_FromHomeAME09000030E02000316NHB_NonHomeBasedAME02000316E02006930NHB_NonHomeBasedIPE02006930E02006929HB_ToHomeIP,21745.0,10688
E02006929E09000030HB_FromHomeAME09000030E02000316NHB_NonHomeBasedIPE02000316E02006930NHB_NonHomeBasedIPE02006930E02006929HB_ToHomeIP,NaN,10689
E02006929E09000030HB_FromHomeAME09000030E02000326NHB_NonHomeBasedIPE02000326E02006930NHB_NonHomeBasedIPE02006930E02006929HB_ToHomeIP,21778.0,10691
E02006929E09000030HB_FromHomeAME09000030E02000331NHB_NonHomeBasedIPE02000331E02006930NHB_NonHomeBasedIPE02006930E02006929HB_ToHomeIP,NaN,10693
E02006929E09000030HB_FromHomeAME09000030E02006929HB_ToHomeIP,NaN,10695
E02006929E09000030HB_FromHomeAME09000030E02006929HB_ToHomeOP2,NaN,10696
E02006929E09000030HB_FromHomeAME09000030E02006930NHB_NonHomeBasedAME02006930E02006929HB_ToHomeIP,NaN,10699
E02006929E09000030HB_FromHomeAME09000030E02006930NHB_NonHomeBasedIPE02006930E02006929HB_ToHomeIP,NaN,10700
E02006929E09000030HB_FromHomeIPE09000030E02000316NHB_NonHomeBasedIPE02000316E02006930NHB_NonHomeBasedIPE02006930E02006929HB_ToHomeIP,NaN,10690
E02006929E09000030HB_FromHomeIPE09000030E02000326NHB_NonHomeBasedIPE02000326E02006930NHB_NonHomeBasedIPE02006930E02006929HB_ToHomeIP,NaN,10692
E02006929E09000030HB_FromHomeIPE09000030E02000331NHB_NonHomeBasedIPE02000331E02006930NHB_NonHomeBasedIPE02006930E02006929HB_ToHomeIP,NaN,10694
E02006929E09000030HB_FromHomeIPE09000030E02006929HB_ToHomeIP,NaN,10697
E02006929E09000030HB_FromHomeIPE09000030E02006929HB_ToHomeOP2,NaN,10698
E02006929E09000030HB_FromHomeIPE09000030E02006930NHB_NonHomeBasedIPE02006930E02006929HB_ToHomeIP,21813.0,10701
E02006930E02006929HB_FromHomeIPE02006929E02006930HB_ToHomeIP,21949.0,10702
E02006930E09000030HB_FromHomeOP1E09000030E02000316NHB_NonHomeBasedAME02000316E02006929NHB_NonHomeBasedAME02006929E02006930HB_ToHomeIP,NaN,10703
E02006930E09000030HB_FromHomeOP1E09000030E02000316NHB_NonHomeBasedAME02000316E02006929NHB_NonHomeBasedIPE02006929E02006930HB_ToHomeIP,NaN,10704
E02006930E09000030HB_FromHomeOP1E09000030E02000316NHB_NonHomeBasedIPE02000316E02006929NHB_NonHomeBasedIPE02006929E02006930HB_ToHomeIP,NaN,10705
E02006930E09000030HB_FromHomeOP1E09000030E02000327NHB_NonHomeBasedIPE02000327E02006929NHB_NonHomeBasedIPE02006929E02006930HB_ToHomeIP,NaN,10706
E02006930E09000030HB_FromHomeOP1E09000030E02000331NHB_NonHomeBasedIPE02000331E02006929NHB_NonHomeBasedIPE02006929E02006930HB_ToHomeIP,NaN,10707
E02006930E09000030HB_FromHomeOP1E09000030E02006927NHB_NonHomeBasedIPE02006927E02006929NHB_NonHomeBasedIPE02006929E02006930HB_ToHomeIP,NaN,10708
E02006930E09000030HB_FromHomeOP1E09000030E02006929NHB_NonHomeBasedAME02006929E02006930HB_ToHomeIP,NaN,10709
E02006930E09000030HB_FromHomeOP1E09000030E02006929NHB_NonHomeBasedIPE02006929E02006930HB_ToHomeIP,NaN,10710
E02006930E09000030HB_FromHomeOP1E09000030E02006931NHB_NonHomeBasedAME02006931E02006929NHB_NonHomeBasedIPE02006929E02006930HB_ToHomeIP,22227.0,10711

In [74]:
d = dict(zip(jn.TripChainId_orig, jn.TripChainId_reverse))

In [75]:
d

{0: 0,
 16: 13,
 25: 22,
 26: 23,
 27: 24,
 28: 25,
 30: 27,
 48: 43,
 49: 44,
 50: 45,
 51: 46,
 52: 47,
 54: 48,
 55: 49,
 56: 50,
 59: 53,
 68: 62,
 80: 74,
 81: 75,
 94: 88,
 96: 90,
 104: 93,
 119: 99,
 184: 139,
 215: 155,
 217: 157,
 231: 171,
 244: 184,
 246: 186,
 248: 188,
 280: 217,
 287: 224,
 409: 312,
 411: 314,
 412: 315,
 414: 317,
 427: 327,
 531: 372,
 536: 377,
 540: 381,
 542: 383,
 557: 393,
 591: 416,
 689: 442,
 690: 443,
 691: 444,
 697: 448,
 698: 449,
 715: 466,
 730: 476,
 739: 485,
 740: 486,
 741: 487,
 768: 499,
 769: 500,
 797: 527,
 803: 533,
 804: 534,
 805: 535,
 826: 553,
 827: 554,
 837: 559,
 850: 571,
 866: 581,
 867: 582,
 874: 587,
 878: 591,
 883: 596,
 886: 599,
 888: 601,
 889: 602,
 900: 608,
 904: 612,
 910: 617,
 918: 623,
 919: 624,
 920: 625,
 923: 628,
 926: 631,
 934: 639,
 935: 640,
 936: 641,
 937: 642,
 938: 643,
 939: 644,
 940: 645,
 941: 646,
 942: 647,
 943: 648,
 945: 650,
 954: 659,
 955: 660,
 960: 665,
 972: 673,
 1019: 695,
 1021: 697,
 1022: 698,
 1023: 699,
 1054: 720,
 1063: 725,
 1091: 743,
 1093: 745,
 1094: 746,
 1096: 748,
 1097: 749,
 1098: 750,
 1106: 756,
 1145: 782,
 1176: 786,
 1188: 797,
 1227: 820,
 1247: 840,
 1250: 843,
 1259: 852,
 1265: 858,
 1266: 859,
 1286: 878,
 1299: 891,
 1321: 912,
 1347: 933,
 1348: 934,
 1366: 949,
 1408: 969,
 1416: 977,
 1468: 1015,
 1519: 1049,
 1524: 1052,
 1525: 1053,
 1527: 1055,
 1528: 1056,
 1535: 1059,
 1560: 1074,
 1561: 1075,
 1562: 1076,
 1563: 1077,
 1564: 1078,
 1565: 1079,
 1604: 1099,
 1655: 1118,
 1696: 1137,
 1704: 1143,
 1705: 1144,
 1708: 1145,
 1716: 1151,
 1782: 1187,
 1790: 1194,
 1806: 1210,
 1851: 1247,
 1864: 1259,
 1882: 1273,
 1896: 1284,
 1954: 1326,
 1955: 1327,
 1956: 1328,
 1957: 1329,
 1958: 1330,
 1959: 1331,
 1960: 1332,
 1961: 1333,
 1962: 1334,
 1963: 1335,
 1976: 1339,
 1977: 1340,
 1989: 1343,
 2136: 1369,
 2195: 1376,
 2228: 1384,
 2392: 1398,
 2504: 1414,
 2568: 1417,
 2574: 1419,
 2617: 1428,
 2620: 1429,
 2621: 1430,
 2633: 1442,
 2634: 1443,
 2638: 1445,
 2641: 1448,
 2642: 1449,
 2643: 1450,
 2646: 1453,
 2661: 1466,
 2679: 1474,
 2686: 1481,
 2692: 1485,
 2694: 1487,
 2695: 1488,
 2702: 1495,
 2703: 1496,
 2712: 1505,
 2748: 1533,
 2749: 1534,
 2750: 1535,
 2751: 1536,
 2752: 1537,
 2754: 1539,
 2758: 1543,
 2762: 1547,
 2774: 1559,
 2785: 1569,
 2790: 1574,
 2793: 1577,
 2795: 1579,
 2796: 1580,
 2797: 1581,
 2802: 1586,
 2805: 1589,
 2809: 1593,
 2818: 1601,
 2836: 1612,
 2844: 1618,
 2848: 1622,
 2872: 1634,
 2879: 1641,
 2881: 1643,
 2886: 1648,
 2888: 1650,
 2893: 1655,
 2903: 1665,
 2905: 1667,
 2909: 1671,
 2941: 1703,
 2963: 1725,
 2964: 1726,
 2965: 1727,
 2966: 1728,
 2967: 1729,
 2968: 1730,
 2969: 1731,
 2970: 1732,
 2971: 1733,
 2972: 1734,
 2973: 1735,
 2974: 1736,
 2975: 1737,
 2976: 1738,
 2977: 1739,
 2993: 1755,
 2994: 1756,
 2995: 1757,
 3162: 1835,
 3170: 1840,
 3208: 1859,
 3216: 1867,
 3219: 1870,
 3374: 1943,
 3701: 2017,
 3706: 2022,
 3707: 2023,
 3732: 2042,
 3739: 2049,
 3748: 2054,
 3749: 2055,
 3818: 2087,
 3876: 2094,
 3877: 2095,
 3878: 2096,
 3933: 2105,
 3938: 2106,
 3946: 2110,
 3965: 2113,
 3966: 2114,
 3967: 2115,
 3969: 2116,
 3970: 2117,
 4057: 2141,
 4152: 2151,
 4153: 2152,
 4220: 2170,
 4252: 2184,
 4272: 2187,
 4419: 2192,
 4420: 2193,
 4423: 2196,
 4458: 2210,
 4484: 2224,
 4536: 2229,
 4548: 2236,
 4621: 2262,
 4624: 2264,
 4625: 2265,
 4632: 2268,
 4649: 2273,
 4650: 2274,
 4651: 2275,
 4679: 2285,
 4691: 2297,
 4693: 2299,
 4695: 2300,
 4696: 2301,
 4697: 2302,
 4703: 2306,
 4705: 2308,
 4711: 2313,
 4714: 2315,
 4715: 2316,
 4717: 2317,
 4720: 2320,
 4724: 2324,
 4728: 2328,
 4729: 2329,
 4730: 2330,
 4732: 2332,
 4734: 2334,
 4736: 2336,
 4737: 2337,
 4738: 2338,
 4739: 2339,
 4740: 2340,
 4741: 2341,
 4742: 2342,
 4752: 2346,
 4756: 2348,
 4759: 2350,
 4763: 2352,
 4775: 2362,
 4776: 2363,
 4783: 2367,
 4797: 2378,
 4802: 2383,
 4804: 2385,
 4810: 2390,
 4824: 2404,
 4845: 2411,
 4852: 2418,
 4856: 2422,
 4889: 2453,
 4904: 2468,
 4905: 2469,
 4906: 2470,
 4911: 2471,
 4917: 2477,
 4918: 2478,
 4919: 2479,
 4920: 2480,
 4922: 2482,
 4934: 2494,
 4936: 2496,
 4939: 2499,
 4941: 2501,
 4943: 2503,
 4944: 2504,
 4945: 2505,
 4946: 2506,
 4955: 2509,
 4958: 2512,
 4966: 2518,
 4996: 2543,
 5021: 2560,
 5023: 2562,
 5024: 2563,
 5044: 2583,
 5062: 2598,
 5142: 2649,
 5160: 2663,
 5176: 2679,
 5177: 2680,
 5180: 2682,
 5185: 2685,
 5209: 2698,
 5213: 2702,
 5258: 2731,
 5294: 2753,
 5295: 2754,
 5326: 2775,
 5339: 2784,
 5384: 2798,
 5495: 2842,
 5522: 2865,
 5601: 2895,
 5623: 2913,
 5709: 2943,
 5760: 2968,
 5803: 3006,
 5816: 3017,
 5819: 3020,
 5845: 3037,
 5855: 3045,
 5884: 3067,
 5953: 3106,
 5955: 3108,
 5959: 3112,
 5991: 3135,
 6030: 3156,
 6139: 3215,
 6183: 3240,
 6319: 3311,
 6322: 3314,
 6369: 3334,
 6376: 3336,
 6377: 3337,
 6386: 3346,
 6395: 3355,
 6403: 3363,
 6406: 3366,
 6408: 3368,
 6432: 3385,
 6439: 3390,
 6440: 3391,
 6441: 3392,
 6442: 3393,
 6443: 3394,
 6445: 3395,
 6446: 3396,
 6502: 3426,
 6508: 3432,
 6509: 3433,
 6527: 3448,
 6548: 3466,
 6551: 3467,
 6556: 3472,
 6558: 3474,
 6566: 3482,
 6621: 3489,
 6645: 3511,
 6658: 3524,
 6673: 3539,
 6691: 3545,
 6707: 3551,
 6711: 3554,
 6713: 3556,
 6730: 3571,
 6850: 3661,
 6875: 3679,
 6909: 3699,
 6911: 3701,
 6959: 3729,
 6982: 3745,
 7074: 3802,
 7103: 3823,
 7118: 3831,
 7149: 3857,
 7211: 3892,
 7212: 3893,
 7248: 3918,
 7249: 3919,
 7251: 3921,
 7252: 3922,
 7257: 3927,
 7259: 3929,
 7279: 3943,
 7294: 3958,
 7321: 3973,
 7322: 3974,
 7323: 3975,
 7324: 3976,
 7325: 3977,
 7326: 3978,
 7327: 3979,
 7328: 3980,
 7329: 3981,
 7330: 3982,
 7332: 3984,
 7338: 3988,
 7349: 3998,
 7383: 4016,
 7470: 4049,
 7525: 4073,
 7528: 4076,
 7594: 4103,
 7596: 4105,
 7610: 4110,
 7698: 4135,
 7809: 4170,
 7823: 4182,
 7836: 4191,
 7898: 4228,
 7931: 4234,
 7940: 4240,
 7945: 4245,
 7951: 4250,
 7952: 4251,
 7958: 4257,
 7963: 4259,
 7964: 4260,
 7971: 4267,
 7973: 4269,
 7974: 4270,
 7975: 4271,
 7976: 4272,
 7977: 4273,
 7978: 4274,
 7979: 4275,
 7981: 4277,
 7982: 4278,
 7983: 4279,
 7985: 4281,
 7987: 4283,
 7989: 4285,
 7991: 4287,
 7996: 4292,
 8005: 4298,
 8030: 4316,
 8035: 4319,
 8036: 4320,
 8037: 4321,
 8040: 4322,
 8059: 4336,
 8061: 4338,
 8069: 4342,
 8070: 4343,
 8071: 4344,
 8077: 4350,
 8079: 4352,
 8082: 4354,
 8086: 4357,
 8087: 4358,
 8088: 4359,
 8089: 4360,
 8090: 4361,
 8203: 4423,
 8335: 4529,
 8337: 4531,
 8441: 4598,
 8444: 4601,
 8942: 4815,
 8943: 4816,
 9064: 4870,
 9065: 4871,
 9217: 4943,
 9364: 4957,
 9378: 4971,
 9547: 5060,
 9765: 5205,
 9766: 5206,
 9768: 5208,
 9814: 5241,
 9920: 5310,
 9926: 5316,
 10068: 5404,
 10160: 5459,
 10477: 5531,
 10478: 5532,
 10616: 5600,
 10746: 5664,
 10954: 5738,
 11033: 5768,
 11062: 5783,
 11706: 5803,
 11708: 5805,
 11721: 5815,
 11723: 5817,
 11747: 5834,
 11750: 5837,
 11756: 5840,
 11759: 5843,
 11760: 5844,
 11761: 5845,
 11763: 5847,
 11773: 5857,
 11775: 5859,
 11776: 5860,
 11784: 5866,
 11793: 5872,
 11800: 5878,
 11801: 5879,
 11802: 5880,
 11803: 5881,
 11828: 5894,
 11839: 5901,
 11890: 5924,
 11916: 5935,
 11973: 5959,
 11977: 5960,
 11979: 5962,
 14757: 5966,
 14768: 5977,
 14776: 5985,
 14778: 5987,
 14781: 5990,
 14787: 5993,
 14803: 6003,
 14808: 6008,
 14809: 6009,
 14810: 6010,
 14811: 6011,
 14813: 6013,
 14816: 6016,
 14839: 6039,
 14847: 6047,
 14863: 6063,
 14864: 6064,
 14867: 6067,
 14880: 6076,
 14906: 6098,
 14915: 6107,
 14918: 6110,
 14924: 6116,
 14942: 6134,
 14945: 6137,
 14948: 6140,
 14951: 6143,
 14952: 6144,
 14953: 6145,
 14960: 6152,
 14962: 6154,
 14969: 6161,
 14970: 6162,
 14971: 6163,
 14972: 6164,
 14973: 6165,
 14974: 6166,
 14975: 6167,
 14977: 6168,
 14978: 6169,
 14990: 6176,
 14995: 6181,
 15048: 6212,
 15062: 6226,
 15071: 6234,
 15073: 6236,
 15074: 6237,
 15104: 6264,
 15121: 6281,
 15122: 6282,
 15124: 6284,
 15126: 6286,
 15143: 6302,
 15144: 6303,
 15146: 6305,
 15162: 6318,
 15163: 6319,
 15166: 6322,
 15172: 6328,
 15239: 6369,
 15243: 6372,
 15264: 6392,
 15265: 6393,
 15269: 6397,
 15270: 6398,
 15274: 6402,
 15278: 6406,
 15285: 6413,
 15289: 6417,
 15306: 6419,
 15317: 6423,
 15335: 6440,
 15336: 6441,
 15337: 6442,
 15338: 6443,
 15339: 6444,
 15345: 6450,
 15346: 6451,
 15348: 6453,
 15349: 6454,
 15352: 6457,
 15354: 6459,
 15357: 6462,
 15361: 6466,
 15362: 6467,
 15363: 6468,
 15364: 6469,
 15375: 6480,
 15399: 6504,
 15403: 6508,
 15405: 6510,
 15406: 6511,
 15407: 6512,
 15411: 6516,
 15416: 6521,
 15418: 6523,
 15421: 6526,
 15430: 6535,
 15432: 6537,
 15433: 6538,
 15435: 6540,
 15437: 6542,
 15439: 6544,
 15443: 6548,
 15466: 6567,
 15472: 6573,
 15480: 6581,
 15482: 6583,
 15486: 6587,
 15487: 6588,
 15494: 6595,
 15495: 6596,
 15496: 6597,
 15497: 6598,
 15498: 6599,
 15501: 6602,
 15502: 6603,
 15504: 6605,
 15506: 6607,
 15507: 6608,
 15508: 6609,
 15509: 6610,
 15513: 6614,
 15532: 6633,
 15533: 6634,
 15535: 6636,
 15539: 6640,
 15543: 6644,
 15560: 6661,
 15563: 6664,
 15570: 6671,
 15572: 6673,
 15576: 6677,
 15588: 6686,
 15591: 6689,
 15592: 6690,
 15593: 6691,
 15597: 6693,
 15598: 6694,
 15599: 6695,
 15600: 6696,
 15611: 6700,
 15625: 6706,
 15626: 6707,
 15627: 6708,
 15631: 6712,
 15640: 6721,
 15655: 6736,
 15657: 6738,
 15662: 6743,
 15664: 6745,
 15666: 6747,
 15668: 6749,
 15674: 6753,
 15680: 6759,
 15707: 6774,
 15719: 6778,
 15760: 6816,
 15763: 6819,
 15767: 6823,
 15768: 6824,
 15769: 6825,
 15787: 6840,
 15788: 6841,
 15805: 6858,
 15807: 6860,
 15808: 6861,
 15809: 6862,
 15813: 6863,
 15858: 6898,
 15866: 6906,
 15867: 6907,
 15868: 6908,
 15869: 6909,
 15898: 6938,
 15899: 6939,
 15900: 6940,
 15902: 6942,
 15903: 6943,
 15904: 6944,
 15914: 6953,
 15922: 6961,
 15930: 6969,
 15937: 6975,
 15945: 6983,
 15969: 7007,
 15971: 7009,
 15973: 7011,
 16002: 7040,
 16003: 7041,
 16018: 7052,
 16068: 7100,
 16070: 7102,
 16073: 7105,
 16093: 7119,
 16102: 7127,
 16110: 7133,
 16112: 7135,
 16116: 7139,
 16117: 7140,
 16130: 7153,
 16131: 7154,
 16138: 7161,
 16161: 7167,
 16162: 7168,
 16167: 7173,
 16172: 7178,
 16173: 7179,
 16174: 7180,
 16178: 7184,
 16180: 7186,
 16181: 7187,
 16184: 7190,
 16207: 7203,
 16210: 7206,
 16217: 7213,
 16230: 7226,
 16236: 7232,
 16243: 7239,
 16244: 7240,
 16247: 7243,
 16251: 7247,
 16254: 7250,
 16256: 7251,
 16281: 7261,
 16282: 7262,
 16321: 7290,
 16329: 7298,
 16330: 7299,
 16331: 7300,
 16335: 7304,
 16336: 7305,
 16339: 7308,
 16341: 7310,
 16353: 7317,
 16354: 7318,
 16355: 7319,
 16356: 7320,
 16357: 7321,
 16360: 7324,
 16363: 7327,
 16367: 7331,
 16371: 7335,
 16379: 7341,
 16387: 7346,
 16389: 7348,
 16393: 7352,
 16394: 7353,
 16395: 7354,
 16396: 7355,
 16409: 7367,
 16412: 7370,
 16416: 7373,
 16423: 7378,
 16424: 7379,
 16425: 7380,
 16426: 7381,
 16430: 7385,
 16436: 7391,
 16439: 7394,
 16443: 7397,
 16444: 7398,
 16445: 7399,
 16447: 7401,
 16451: 7404,
 16453: 7406,
 16454: 7407,
 16457: 7410,
 16458: 7411,
 16460: 7413,
 16464: 7417,
 16468: 7421,
 16470: 7423,
 16474: 7427,
 16475: 7428,
 16476: 7429,
 16487: 7440,
 16488: 7441,
 16492: 7445,
 16497: 7450,
 16505: 7458,
 16508: 7460,
 16518: 7468,
 16519: 7469,
 16520: 7470,
 16526: 7473,
 16537: 7484,
 16543: 7490,
 16546: 7492,
 16549: 7495,
 16550: 7496,
 16551: 7497,
 16561: 7507,
 16562: 7508,
 16569: 7513,
 16579: 7523,
 16580: 7524,
 16581: 7525,
 16582: 7526,
 16583: 7527,
 16584: 7528,
 16585: 7529,
 16586: 7530,
 16587: 7531,
 16588: 7532,
 16589: 7533,
 16590: 7534,
 16592: 7536,
 16593: 7537,
 16594: 7538,
 16595: 7539,
 16596: 7540,
 16597: 7541,
 16599: 7542,
 16600: 7543,
 16603: 7546,
 16609: 7552,
 16622: 7564,
 16632: 7574,
 16633: 7575,
 16640: 7582,
 16642: 7584,
 16643: 7585,
 16644: 7586,
 16645: 7587,
 16646: 7588,
 16647: 7589,
 16648: 7590,
 16649: 7591,
 16650: 7592,
 16651: 7593,
 16652: 7594,
 16653: 7595,
 16654: 7596,
 16658: 7600,
 16663: 7605,
 16664: 7606,
 16665: 7607,
 16666: 7608,
 16667: 7609,
 16668: 7610,
 16669: 7611,
 16670: 7612,
 16671: 7613,
 16672: 7614,
 16673: 7615,
 16674: 7616,
 16675: 7617,
 16676: 7618,
 16677: 7619,
 16678: 7620,
 16679: 7621,
 16680: 7622,
 16681: 7623,
 16682: 7624,
 16683: 7625,
 16684: 7626,
 16686: 7627,
 16689: 7630,
 16692: 7633,
 16704: 7638,
 16713: 7644,
 16722: 7647,
 16723: 7648,
 16726: 7651,
 16730: 7652,
 16731: 7653,
 16736: 7658,
 16737: 7659,
 16738: 7660,
 16744: 7663,
 16755: 7673,
 16761: 7679,
 16764: 7682,
 16765: 7683,
 16766: 7684,
 16767: 7685,
 16776: 7690,
 16778: 7692,
 16779: 7693,
 16780: 7694,
 16782: 7695,
 16786: 7697,
 16794: 7700,
 16801: 7703,
 16802: 7704,
 16803: 7705,
 16807: 7708,
 16815: 7714,
 16820: 7718,
 16822: 7720,
 16834: 7728,
 16841: 7735,
 16842: 7736,
 16843: 7737,
 16850: 7744,
 16851: 7745,
 16875: 7766,
 16876: 7767,
 16877: 7768,
 16879: 7770,
 16887: 7775,
 16889: 7776,
 16902: 7789,
 16904: 7791,
 16974: 7836,
 17059: 7864,
 17089: 7891,
 17099: 7901,
 17103: 7905,
 17112: 7914,
 17119: 7921,
 17121: 7923,
 17126: 7928,
 17137: 7938,
 17144: 7945,
 17146: 7947,
 17149: 7950,
 17176: 7972,
 17178: 7974,
 17221: 8017,
 17233: 8028,
 17292: 8079,
 17293: 8080,
 17321: 8102,
 17322: 8103,
 17335: 8114,
 17369: 8143,
 17379: 8153,
 17380: 8154,
 17381: 8155,
 17382: 8156,
 17384: 8158,
 17394: 8164,
 17395: 8165,
 ...}

In [83]:
tc_map = pd.DataFrame.from_dict(d, orient='index', )
tc_map.index.name = 'tc_id_original'
tc_map.columns = ['tc_id_reverse']
tc_map = tc_map.squeeze()
tc_map

tc_id_original
0            0
16          13
25          22
26          23
27          24
28          25
30          27
48          43
49          44
50          45
51          46
52          47
54          48
55          49
56          50
59          53
68          62
80          74
81          75
94          88
96          90
104         93
119         99
184        139
215        155
217        157
231        171
244        184
246        186
248        188
         ...
20579    10311
20626    10350
20664    10374
20666    10376
20704    10405
20753    10438
20786    10456
20787    10457
20790    10460
20791    10461
20797    10467
20954    10515
21109    10535
21114    10540
21172    10573
21179    10580
21239    10610
21320    10618
21367    10649
21369    10651
21524    10671
21525    10672
21538    10679
21539    10680
21540    10681
21745    10688
21778    10691
21813    10701
21949    10702
22227    10711
Name: tc_id_reverse, Length: 1210, dtype: int64

In [85]:
tc_map.to_clipboard(header=True)