In [51]:
import pandas as pd

In [52]:
pd.set_option('display.max_colwidth', 1000)

In [53]:
%store -r tcs_defs_optim
%store -r tcs_defs_orig

In [54]:
tcs_defs_optim = tcs_defs_optim.copy()
tcs_defs_orig = tcs_defs_orig.copy()

In [55]:
tcs_defs_orig.head(2)

            OrigZoneId DestZoneId      Purpose TimePeriod
TripChainId
0            E02000313  E02000314  HB_FromHome         IP
0            E02000314  E02000313    HB_ToHome         IP

In [56]:
tcs_defs_optim.head(2)

            OrigZoneId DestZoneId      Purpose TimePeriod
TripChainId
0            E02000313  E02000314  HB_FromHome         IP
0            E02000314  E02000313    HB_ToHome         IP

In [57]:
tcs_defs_orig['LegDescr'] = tcs_defs_orig.apply(lambda x: '_'.join(x), axis=1)
tcs_defs_orig = tcs_defs_orig[['LegDescr']]
tcs_defs_orig.head(2)

                                       LegDescr
TripChainId
0            E02000313_E02000314_HB_FromHome_IP
0              E02000314_E02000313_HB_ToHome_IP

In [58]:
tcs_defs_optim['LegDescr'] = tcs_defs_optim.apply(lambda x: '_'.join(x), axis=1)
tcs_defs_optim = tcs_defs_optim[['LegDescr']]
tcs_defs_optim.head(2)

                                       LegDescr
TripChainId
0            E02000313_E02000314_HB_FromHome_IP
0              E02000314_E02000313_HB_ToHome_IP

In [59]:
dfg_orig = tcs_defs_orig.groupby('TripChainId').sum().reset_index()
dfg_optim = tcs_defs_optim.groupby('TripChainId').sum().reset_index()

In [60]:
jn = pd.merge(left=dfg_orig, right=dfg_optim, on='LegDescr', how='outer', suffixes=['_Orig', '_Optim'])
jn.drop('LegDescr', axis=1, inplace=True)

In [61]:
jn.to_clipboard(sep=',')