In [1]:
import pandas as pd

In [2]:
df1 = pd.read_clipboard()
df1.set_index('TripChainId', inplace=True)

In [3]:
df2 = pd.read_clipboard()
df2.set_index('TripChainId', inplace=True)

In [4]:
df1

            OrigZoneId DestZoneId           Purpose TimePeriod
TripChainId
0            E02000313  E02000314       HB_FromHome         IP
0            E02000314  E02000313         HB_ToHome         IP
16           E02000313  E02000314       HB_FromHome         IP
16           E02000314  E02000318  NHB_NonHomeBased         IP
16           E02000318  E02006786  NHB_NonHomeBased         IP
16           E02006786  E02000313         HB_ToHome         PM
25           E02000313  E02000314       HB_FromHome         IP
25           E02000314  E02000321  NHB_NonHomeBased         IP
25           E02000321  E09000004  NHB_NonHomeBased         PM
25           E09000004  E02000313         HB_ToHome         PM
26           E02000313  E02000314       HB_FromHome         IP
26           E02000314  E02006786  NHB_NonHomeBased         IP
26           E02006786  E02000313         HB_ToHome         IP
27           E02000313  E02000314       HB_FromHome         IP
27           E02000314  E02006786  NHB_NonHomeBased         IP
27           E02006786  E02000313         HB_ToHome         PM
28           E02000313  E02000314       HB_FromHome         IP
28           E02000314  E02006786  NHB_NonHomeBased         PM
28           E02006786  E02000313         HB_ToHome         PM
30           E02000313  E02000314       HB_FromHome         IP
30           E02000314  E02006786  NHB_NonHomeBased         IP
30           E02006786  E09000004  NHB_NonHomeBased         IP
30           E09000004  E02000313         HB_ToHome         PM
48           E02000313  E02006786       HB_FromHome         AM
48           E02006786  E02000313         HB_ToHome         IP
49           E02000313  E02006786       HB_FromHome         AM
49           E02006786  E02000313         HB_ToHome         PM
50           E02000313  E02006786       HB_FromHome         IP
50           E02006786  E02000313         HB_ToHome         IP
51           E02000313  E02006786       HB_FromHome         IP
...                ...        ...               ...        ...
21524        E02006930  E02000326  NHB_NonHomeBased         IP
21524        E02000326  E09000030  NHB_NonHomeBased         IP
21524        E09000030  E02006929         HB_ToHome         IP
21525        E02006929  E02006930       HB_FromHome         IP
21525        E02006930  E02000326  NHB_NonHomeBased         IP
21525        E02000326  E09000030  NHB_NonHomeBased         IP
21525        E09000030  E02006929         HB_ToHome        OP2
21538        E02006929  E02006930       HB_FromHome         IP
21538        E02006930  E02006929         HB_ToHome         IP
21539        E02006929  E02006930       HB_FromHome        OP1
21539        E02006930  E02006929         HB_ToHome         IP
21540        E02006929  E02006930       HB_FromHome        OP1
21540        E02006930  E02006929         HB_ToHome        OP1
21745        E02006929  E09000030       HB_FromHome         AM
21745        E09000030  E02000316  NHB_NonHomeBased         AM
21745        E02000316  E02006930  NHB_NonHomeBased         IP
21745        E02006930  E02006929         HB_ToHome         IP
21778        E02006929  E09000030       HB_FromHome         AM
21778        E09000030  E02000326  NHB_NonHomeBased         IP
21778        E02000326  E02006930  NHB_NonHomeBased         IP
21778        E02006930  E02006929         HB_ToHome         IP
21813        E02006929  E09000030       HB_FromHome         IP
21813        E09000030  E02006930  NHB_NonHomeBased         IP
21813        E02006930  E02006929         HB_ToHome         IP
21949        E02006930  E02006929       HB_FromHome         IP
21949        E02006929  E02006930         HB_ToHome         IP
22227        E02006930  E09000030       HB_FromHome        OP1
22227        E09000030  E02006931  NHB_NonHomeBased         AM
22227        E02006931  E02006929  NHB_NonHomeBased         IP
22227        E02006929  E02006930         HB_ToHome         IP

[4289 rows x 4 columns]

In [5]:
df2

            OrigZoneId DestZoneId           Purpose TimePeriod
TripChainId
0            E02000313  E02000314       HB_FromHome         IP
0            E02000314  E02000313         HB_ToHome         IP
1            E02000313  E02000314       HB_FromHome         IP
1            E02000314  E02000315  NHB_NonHomeBased         IP
1            E02000315  E02006786  NHB_NonHomeBased         IP
1            E02006786  E02000313         HB_ToHome         IP
2            E02000313  E02000314       HB_FromHome         IP
2            E02000314  E02000315  NHB_NonHomeBased         IP
2            E02000315  E02006786  NHB_NonHomeBased         IP
2            E02006786  E02000313         HB_ToHome         PM
3            E02000313  E02000314       HB_FromHome         IP
3            E02000314  E02000315  NHB_NonHomeBased         IP
3            E02000315  E09000004  NHB_NonHomeBased         PM
3            E09000004  E02000313         HB_ToHome         PM
4            E02000313  E02000314       HB_FromHome         IP
4            E02000314  E02000316  NHB_NonHomeBased         IP
4            E02000316  E02006786  NHB_NonHomeBased         IP
4            E02006786  E02000313         HB_ToHome         IP
5            E02000313  E02000314       HB_FromHome         IP
5            E02000314  E02000316  NHB_NonHomeBased         IP
5            E02000316  E02006786  NHB_NonHomeBased         IP
5            E02006786  E02000313         HB_ToHome         PM
6            E02000313  E02000314       HB_FromHome         IP
6            E02000314  E02000316  NHB_NonHomeBased         IP
6            E02000316  E02006786  NHB_NonHomeBased         PM
6            E02006786  E02000313         HB_ToHome         PM
7            E02000313  E02000314       HB_FromHome         IP
7            E02000314  E02000316  NHB_NonHomeBased         IP
7            E02000316  E09000004  NHB_NonHomeBased         IP
7            E09000004  E02000313         HB_ToHome         IP
...                ...        ...               ...        ...
10704        E02006930  E09000030       HB_FromHome        OP1
10704        E09000030  E02000316  NHB_NonHomeBased         AM
10704        E02000316  E02006929  NHB_NonHomeBased         IP
10704        E02006929  E02006930         HB_ToHome         IP
10705        E02006930  E09000030       HB_FromHome        OP1
10705        E09000030  E02000316  NHB_NonHomeBased         IP
10705        E02000316  E02006929  NHB_NonHomeBased         IP
10705        E02006929  E02006930         HB_ToHome         IP
10706        E02006930  E09000030       HB_FromHome        OP1
10706        E09000030  E02000327  NHB_NonHomeBased         IP
10706        E02000327  E02006929  NHB_NonHomeBased         IP
10706        E02006929  E02006930         HB_ToHome         IP
10707        E02006930  E09000030       HB_FromHome        OP1
10707        E09000030  E02000331  NHB_NonHomeBased         IP
10707        E02000331  E02006929  NHB_NonHomeBased         IP
10707        E02006929  E02006930         HB_ToHome         IP
10708        E02006930  E09000030       HB_FromHome        OP1
10708        E09000030  E02006927  NHB_NonHomeBased         IP
10708        E02006927  E02006929  NHB_NonHomeBased         IP
10708        E02006929  E02006930         HB_ToHome         IP
10709        E02006930  E09000030       HB_FromHome        OP1
10709        E09000030  E02006929  NHB_NonHomeBased         AM
10709        E02006929  E02006930         HB_ToHome         IP
10710        E02006930  E09000030       HB_FromHome        OP1
10710        E09000030  E02006929  NHB_NonHomeBased         IP
10710        E02006929  E02006930         HB_ToHome         IP
10711        E02006930  E09000030       HB_FromHome        OP1
10711        E09000030  E02006931  NHB_NonHomeBased         AM
10711        E02006931  E02006929  NHB_NonHomeBased         IP
10711        E02006929  E02006930         HB_ToHome         IP

[41316 rows x 4 columns]

In [48]:
dfg1 = df1.groupby(level=0)
dfg2 = df2.groupby(level=0)

d = {}
for k1, g1 in dfg1:
    for k2, g2 in dfg2: 
        if g1.equals(g2):
            d[k1] = k2
            break

KeyboardInterrupt:

In [8]:
cols = ['OrigZoneId', 'DestZoneId', 'Purpose', 'TimePeriod']
df1['tmp'] = df1[cols].values.sum(axis=1)
df2['tmp'] = df2[cols].values.sum(axis=1)

In [11]:
dfg1 = df1.groupby(level=0)['tmp'].sum()
dfg2 = df2.groupby(level=0)['tmp'].sum()

In [15]:
dfg2.isin(dfg1)

TripChainId
0         True
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13        True
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22        True
23        True
24        True
25        True
26       False
27        True
28       False
29       False
         ...
10682    False
10683    False
10684    False
10685    False
10686    False
10687    False
10688     True
10689    False
10690    False
10691     True
10692    False
10693    False
10694    False
10695    False
10696    False
10697    False
10698    False
10699    False
10700    False
10701     True
10702     True
10703    False
10704    False
10705    False
10706    False
10707    False
10708    False
10709    False
10710    False
10711     True
Name: tmp, Length: 10712, dtype: bool

In [51]:
g20

            OrigZoneId DestZoneId      Purpose TimePeriod
TripChainId
0            E02000313  E02000314  HB_FromHome         IP
0            E02000314  E02000313    HB_ToHome         IP